/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageJPanel.java
 *
 * 
 */

package desktopapplication1;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Administrator
 */
public class ImageJPanel extends javax.swing.JPanel {

    /** Creates new form ImageJPanel */
    BufferedImage i;
    File f;
    public ImageJPanel() {
        initComponents();

    }
    public void initalise(File f)
    {
        try
        {
            i = ImageIO.read(f);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
   public void paintComponent(Graphics g)
    {
        super.paintComponent(g); // Do the original draw
        g.drawImage(i,0,0,new ImageJPanel().getWidth(),new ImageJPanel().getHeight(),new ImageJPanel());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
