/*
 * To change this template, choose Tools | Templates
 * 
 * and open the template in the editor.
 */

/*
 * LoginImagePanel.java
 *
 * 
 */

package desktopapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Random;
import java.util.*;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
   import java.io.*;
   import java.sql.*;

/**
 *
 * @author Administrator
 */
public class LoginImagePanel extends javax.swing.JFrame {

    /** Creates new form LoginImagePanel */
    public LoginImagePanel()
    {
        initComponents();
        
        loginimagePanel.addMouseListener(new MouseListener(){
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
         System.out.println("mouse clicked"+evt.getX()+"  "+evt.getY());
         x = evt.getX();
         y = evt.getY();
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/graphicalpassword","root","admin");
            st = con.createStatement();
            rs = st.executeQuery("select sound from imageselection where username='"+LoginFrame.loginID+"' and xcordinate='"+x+"' and ycordinate='"+y+"'");
            if(rs.next())
            {
         //    String[] roseindia={"Dolphin","Duck","Lion","Rhino","Bird"};
         //Random randomGenerator = new Random();
         
         System.out.println(LoginFrame.loginID);
             // for(int i=0;i<5;i++)
              //{
  //System.out.println(roseindia[i]);
         //int randomInt = randomGenerator.nextInt(5);
         musicfile = rs.getString(1);


            }
            else
            {
                 String[] roseindia={"beach2 (ocean surf)","gabbiano","gull","lg_steam_gulls","seagull","seaside-01"};
         Random randomGenerator = new Random();
       //  System.out.println("mouse clicked"+evt.getX()+"  "+evt.getY());
        // x = evt.getX();
       //  y = evt.getY();
        System.out.println(LoginFrame.loginID);
             // for(int i=0;i<5;i++)
              //{
  //System.out.println(roseindia[i]);
         int randomInt = randomGenerator.nextInt(5);
         musicfile = roseindia[randomInt];
	            //rd=req.getRequestDispatcher("/failure.jsp");
	           // out.println("welcome");
	    }
	        //rd.forward(req,res);
        } catch(Exception e2)
        {
            //System.out.println("Exception : "+e2.toString());
              //out.println(e2);
        }










        
             // }
        p =new PlayWavFile(musicfile);
        Thread t=new Thread(p);
        t.start();
        }

        public void mousePressed(MouseEvent e) {}

        public void mouseReleased(MouseEvent e) {}

        public void mouseEntered(MouseEvent e) {}

        public void mouseExited(MouseEvent e) {}
        });
        displayImage();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginimagePanel = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {
                super.paintComponent(g); // Do the original draw
                g.drawImage(i,0,0,loginimagePanel.getWidth(),loginimagePanel.getHeight(),loginimagePanel);
                // g.setColor(Color.WHITE);

                // g.fillOval(xCordinate, yCordinate, 5, 5);
                // g.fillOval(randomXcordinate,randomYcordinate,5,5);

            }
        }
        ;
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginimagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        loginimagePanel.setPreferredSize(new java.awt.Dimension(548, 425));

        javax.swing.GroupLayout loginimagePanelLayout = new javax.swing.GroupLayout(loginimagePanel);
        loginimagePanel.setLayout(loginimagePanelLayout);
        loginimagePanelLayout.setHorizontalGroup(
            loginimagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        loginimagePanelLayout.setVerticalGroup(
            loginimagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GetClickedpoints");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginimagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginimagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton3.enable();
        if(login.registrationVector.size()==0)
        {
           //new JOptionPane().showMessageDialog(this,"No More Images","Warning Message",JOptionPane.INFORMATION_MESSAGE);
          calculateEucledianDistance();

        }
        else
        {
            System.out.println("loginVector.size()"+loginVector.size());
            displayImage();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.disable();
        imagevector = new ImageVector(imageName,x,y);
        loginVector.add(imagevector);
        System.out.println("loginVector.size()"+loginVector.size());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        JOptionPane.showMessageDialog(rootPane, "UnAuthorised User Operation");
//        for(int i=0;i<loginVector.size();i++)
//        {
//            imagevector = (ImageVector) loginVector.elementAt(i);
//            System.out.println(imagevector.image+" "+imagevector.xCordinate+" "+imagevector.yCordiante);
//        }
    }//GEN-LAST:event_jButton2ActionPerformed

     public void displayImage()
     {
        imagevector = (ImageVector)login.registrationVector.firstElement();
        try
        {
                Random r=new Random();
                randomXcordinate = r.nextInt(100);
                randomYcordinate = r.nextInt(100);
                i = ImageIO.read(new File(imagevector.image.toString()));
                imageName = imagevector.image.toString();
                xCordinate = imagevector.xCordinate;
                yCordinate = imagevector.yCordiante;
                repaint();
                loginVector1.add(new ImageVector(imageName,xCordinate,yCordinate));
                login.registrationVector.remove(imagevector);
        }
        catch(Exception e){e.printStackTrace();}
     }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginImagePanel().setVisible(true);
            }
        });
    }

    public void displayImage1()
     {
      //  imagevector = (ImageVector)login.registrationVector.firstElement();
        try
        {
                Random r=new Random();
                randomXcordinate = r.nextInt(100);
                randomYcordinate = r.nextInt(100);

                int a=r.nextInt(9);
                i = ImageIO.read(new File("C:/GraphicalPassword/Resource/"+a+".bmp"));
                imageName = imagevector.image.toString();
                xCordinate = imagevector.xCordinate;
                yCordinate = imagevector.yCordiante;
                repaint();
                loginVector1.add(new ImageVector(imageName,xCordinate,yCordinate));
                login.registrationVector.remove(imagevector);
        }
        catch(Exception e){e.printStackTrace();}
     }

    

    //Eucledian Distance calculation
    public void calculateEucledianDistance()
    {
        double result=0,result1=0;
        for(int i=0;i<loginVector.size();i++)
        {
            imagevector = (ImageVector) loginVector.get(i);
            imagevector1 = (ImageVector) loginVector1.get(i);
try

{
            double x = imagevector1.xCordinate - imagevector.xCordinate;
            System.out.println(imagevector1.xCordinate+" - "+ imagevector.xCordinate);
            double y = imagevector1.yCordiante - imagevector.yCordiante;
            System.out.println(imagevector1.xCordinate+" - "+imagevector.xCordinate);
            result = result + ((x * x)+ (y * y));
            
             result1 = Math.abs(Math.sqrt(result));
             if(result1>=0 && result1<=10)
                 flag=0;
             else
                 flag=1;
                 
}
catch(Exception e){e.printStackTrace();}
        }
        
             
              System.out.println("result***************"+result1);
            //if(result1>=0 && result1 < 10)
              if(flag==0)
            {
                this.setVisible(false);
                Thread t=new Thread( new PlayWavFile(new LoginFrame().Sound));
                t.start();
                //new Main().startServer();
                String cmd = null;
            String WIN_PATH = "rundll32";
            String WIN_FLAG = "url.dll,FileProtocolHandler";
            try {
                  cmd = WIN_PATH + " " + WIN_FLAG + " " + "http://www.gmail.com";
                  Process p = Runtime.getRuntime().exec(cmd);
                }
            catch(Exception e){ System.out.println(e); }

            }
            else
            {
             // JOptionPane.showMessageDialog(this, "Invalid User","Error",JOptionPane.INFORMATION_MESSAGE, null);
                   displayImage1();



             // Thread t1=new Thread( new PlayWavFile(dummy));
              //t1.start();
             
              
            }
//}
//catch(Exception e){e.printStackTrace();}
//}
       
        System.out.println("result___________"+result1);
    }
  public PlayWavFile p ;
    public Thread t;
    public String musicfile;
    BufferedImage i;
    LoginFrame login = new LoginFrame();
    ImageVector imagevector;
    ImageVector imagevector1;
    Vector loginVector = new Vector<ImageVector>();
    Vector loginVector1 = new Vector<ImageVector>();
    String imageName = "";
    public int x;
    public int y;
    public int xCordinate;
    public int yCordinate;
    public int randomXcordinate;
    public int randomYcordinate;
    public String dummy="Siren";
    public int flag;

     Connection con=null;
    Statement st=null;
    ResultSet rs=null;

    public int xCordiante;
    public int yCordiante;
    public ImageVector vector;
    public static String Sound;
 MyConnection connect=null;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel loginimagePanel;
    // End of variables declaration//GEN-END:variables

}
