/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * 
 */

package desktopapplication1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.sql.*;
/**
 *
 * @author Administrator
 */
public class RegistrationImagePanel extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
   // public File f= new File("C:/Resource/1.bmp");
    public BufferedImage i;
    public static int x;
    public static int y;
    
    public static File f;
    RegistrationFrame login;
    //private PlayWavFile p;
    public RegistrationImagePanel() {
        initComponents();
        System.out.println("size"+ imagePanel.getHeight()+" "+imagePanel.getWidth());
        imagePanel.setSize(new Dimension(20,20));
        imagePanel.addMouseListener(new MouseListener(){
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {

           musicfile = soundComboBox.getSelectedItem().toString();
        p =new PlayWavFile(musicfile);
        Thread t=new Thread(p);
        t.start();
            System.out.println("mouse clicked"+evt.getX()+"  "+evt.getY());
              x = evt.getX();
              y = evt.getY();

              

        }
        public void mousePressed(MouseEvent e) {}

        public void mouseReleased(MouseEvent e) {}

        public void mouseEntered(MouseEvent e) {}

        public void mouseExited(MouseEvent e) {}
        });
        if(login ==null)
        {
            login = new RegistrationFrame();
        }
         dbDataExtraction();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel()
        {
            public void paintComponent(Graphics g)
            {
                super.paintComponent(g); // Do the original draw
                g.drawImage(i,0,0,imagePanel.getWidth(),imagePanel.getHeight(),imagePanel);

            }

        }
        ;
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        soundComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" ImagePanel Form");
        setResizable(false);

        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagePanel.setPreferredSize(new java.awt.Dimension(548, 425));

        jButton2.setText("Load Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("getClickPoints");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Done");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        soundComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(soundComboBox, 0, 129, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(soundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton3.enable();
            try
            {
                JFileChooser chooser = new JFileChooser("C:\\GraphicalPassword\\Resource");
                int returnVal = chooser.showOpenDialog(this);
                if(returnVal == JFileChooser.APPROVE_OPTION)
                {
                    f = chooser.getSelectedFile();
                    i = ImageIO.read(f);
                }
                 repaint();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
    }//GEN-LAST:event_jButton2ActionPerformed
 public void dbDataExtraction()
   {
       try{
       Connection con1= new MyConnection().dbConnection();
       java.sql.Statement st = con1.createStatement();
       ResultSet rs = st.executeQuery("select * from musicfiles ");
       while(rs.next())
       {
           soundComboBox.addItem(rs.getString("Name"));
       }
       }
       catch(Exception e){e.printStackTrace();}
   }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("mouse position"+x+"  "+y);
        vect = new ImageVector(f.toString(),x,y);
        v1.add(vect);
        jButton3.disable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try
        {
                java.sql.Connection con =new MyConnection().dbConnection();
                PreparedStatement st = con.prepareStatement("insert into imageselection values(?,?,?,?,?)");
                for(int i=0;i<v1.size();i++)
                {
                        vect1 = v1.elementAt(i);

                        st.setString(1,login.userID);
                        st.setString(2,vect1.image);
                        st.setInt(3,vect1.xCordinate);
                        st.setInt(4,vect1.yCordiante);
                        st.setString(5,musicfile);
                        st.executeUpdate();
                        System.out.println(vect1.image+" "+vect1.xCordinate+" "+vect1.yCordiante+ " "+musicfile);
                }

    this.setVisible(false);
    new FirstFrame().setVisible(true);
    
        }
        catch(Exception e1)
        {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void soundComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundComboBoxActionPerformed
        // TODO add your handling code here:
        // t.stop();
  
   
     
        musicfile = soundComboBox.getSelectedItem().toString();
        p =new PlayWavFile(musicfile);
        Thread t=new Thread(p);
        t.start();
}//GEN-LAST:event_soundComboBoxActionPerformed

  

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationImagePanel().setVisible(true);
            }
        });
    }
  public PlayWavFile p ;
    public Thread t;
    public String musicfile;
    Vector<ImageVector> v1 = new Vector<ImageVector>();
    ImageVector vect,vect1,vect2;
    ImageJPanel panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox soundComboBox;
    // End of variables declaration//GEN-END:variables

}
